//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class GarageEntities : DbContext
{
    public GarageEntities()
        : base("name=GarageEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Product> Product { get; set; }
    public virtual DbSet<ProductType> ProductType { get; set; }
    public virtual DbSet<Purchase> Purchase { get; set; }
    public virtual DbSet<UserInformation> UserInformation { get; set; }
}
